name: compose-post-service

ports:
  - port: 9090
    targetPort: 9090

container:
  command: ComposePostService
  image: deathstarbench/social-network-microservices
  name: compose-post-service
  ports: 
  - containerPort: 9090

  resources:
    requests:
      cpu: "1m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"

configMaps:
  - name: jaeger-config.yml
    mountPath: /social-network-microservices/config/jaeger-config.yml
    value: jaeger-config

  - name: service-config.json
    mountPath: /social-network-microservices/config/service-config.json
    value: service-config
