name: mongodb-reservation

replicas: 1

ports:
  - port: 27017
    targetPort: 27017

container:
  image: mongo
  imageVersion: 5.0
  name: hotel-reserv-reservation-mongo
  ports:
  - containerPort: 27017
